### PR TITLE
Chinese translation——zh-CN.ini

### PR DESCRIPTION
**Pull request by HZA336**
Chinese translation.

### CODE REVIEW

**Comment by bozbez** [comment]
Thanks for the translation - could you update the "Include process tree" translation to match 312c7a46eed72b6ca808f450e4d12476ffa3c2c1.

**Comment by HZA336** [comment]
IncludeProcessTree="包括进程树"
ExcludeProcessTree="采集所选窗口之外的所有音频"

已补充，但在我使用之前，我不确定我的翻译是否准确。
Google Translate:
It has been added, but before I use it, I am not sure whether my translation is accurate.

**Review by DemoJameson — CHANGES_REQUESTED** [review]
建议与 OBS 中文语言统一：
Mode.Hotkey="用快捷键采集前台窗口"
Window.Priority.Exe="匹配标题，否则查找相同可执行程序的窗口"
Hotkey.Start="采集前台窗口"
Hotkey.Stop="停止采集"

错误翻译：
RecaptureRate="重新采集速率"

需要删除：
IncludeProcessTree

**Comment by bozbez** [comment]
@HZA336 could you review/implement the suggested changes if they are appropriate?

**Comment by HZA336** [comment]
> 如果建议的更改是适当的，您@HZA336可以审查/实施这些更改？
已修改错误翻译，但其他部分未按照“DemoJameson”建议进行修改，因为原翻译虽然并不准确，但是与OBS原版中文翻译相同，所以做出了取舍。
The incorrect translation has been modified, but other parts have not been modified as suggested by "DemoJameson". Although the original translation is not accurate, it is the same as the original Chinese translation of OBS, so a trade-off was made.

**Comment by DemoJameson** [comment]
你的翻译就是因为与 OBS 原中文不一样我才会提出修改意见，请参照
https://github.com/obsproject/obs-studio/blob/master/plugins/win-capture/data/locale/zh-CN.ini

另外，请删除不再使用的 `IncludeProcessTree` 和加上新增的 `Name`
https://github.com/bozbez/win-capture-audio/commit/be7907f4430e2d0f728eabe35d068c8467987a92

**Comment by HZA336** [comment]
> 你的翻译就是因为与 OBS 原中文不一样我才会提出修改意见，请参照
> https://github.com/obsproject/obs-studio/blob/master/plugins/win-capture/data/locale/zh-CN.ini
> 
> 另外，请删除不再使用的 `IncludeProcessTree` 和加上新增的 `Name`
> [be7907f](https://github.com/bozbez/win-capture-audio/commit/be7907f4430e2d0f728eabe35d068c8467987a92)

抱歉，重新核实了一下，你的翻译是正确的，已修改。
Sorry, I checked again. Your translation is correct and has been modified.

**Review by DemoJameson — CHANGES_REQUESTED** [review]
Hotkey.Stop 应为"停止捕获"非"停用捕获"

**Review by DemoJameson — APPROVED** [review]

**Comment by HZA336** [comment]
> Hotkey.Stop 应为"停**止**捕获"非"停**用**捕获"

已修改（这是我第一次提交文件，还真是漏洞百出，感谢校正......）
Modified (this is the first time I submitted a document, it is really full of loopholes, thanks for the correction...)

**Pull request merged**
